### ISSUE TITLE
goroutine 21498 [IO wait]

### ISSUE THREAD

**Issue by zsimon2016** [funny/link#80]
goroutine 21498 [IO wait]:
internal/poll.runtime_pollWait(0x7f04076060a8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000474380, 0xc000912680, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000474380, {0xc000912680, 0x80, 0x80})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000474380, {0xc000912680, 0x40c974, 0x7f042e5d25b8})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000416068, {0xc000912680, 0x7f042e5d25b8, 0x80})
	/usr/local/go/src/net/net.go:183 +0x45
io.ReadAtLeast({0xa455c0, 0xc000416068}, {0xc000912680, 0x80, 0x80}, 0x1)
	/usr/local/go/src/io/io.go:328 +0x9a
github.com/xxx/goclient.(*ProtocolCodec).Receive(0xc0002e12c0)
	/var/vendor/goclient/protocol.go:115 +0x1b7
github.com/funny/link.(*Session).Receive(0xc00077c280)
	/var/vendor/github.com/funny/link/session.go:92 +0xa6
github.com/xxx/goclient.sessionHandler.HandleSession({0xc0002e5420, 0x0}, 0xc00077c280)
	/var/goclient/session_handler.go:38 +0x31f
github.com/funny/link.(*Server).Serve.func1()
	/var/vendor/github.com/funny/link/server.go:53 +0xb2
created by github.com/funny/link.(*Server).Serve
	/var/vendor/github.com/funny/link/server.go:46 +0x29

**Comment by jettyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
